# Generated by Django 3.2.4 on 2021-07-21 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9)),
                ('disciplina', models.CharField(choices=[('Velocista', 'Velocista'), ('Medio fondo', 'Medio fondo'), ('Fondista', 'Fondista')], max_length=20)),
                ('edad', models.DateField()),
                ('categoria', models.CharField(max_length=10)),
                ('federado', models.BooleanField()),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(choices=[('Málaga-CAR', 'Málaga-CAR'), ('Antequera', 'Antequera')], max_length=20)),
                ('prueba', models.CharField(choices=[('60m', '60m'), ('100m', '100m'), ('200m', '200m'), ('400m', '400m'), ('800m', '800m'), ('1500m', '1500m'), ('3000m', '3000m'), ('5000m', '5000m'), ('10000m', '10000m')], max_length=10)),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
