# Generated by Django 3.2.4 on 2021-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_alter_atleta_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=9),
        ),
    ]
